version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
      standard: "PSR12"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php

exclude_patterns:
  - "tests/"
  - "vendor/"
  - "*.*"
