language: php
php:
  - '8.0'

os: linux
dist: focal

# Git branches
branches:
  only:
    - '1.0'

install:
  - composer install

before_script:
  # Prepare code coverage report for CodeClimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: php -d xdebug.mode="develop,coverage,debug,gcstats,profile,trace" ./vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  # Send code coverage report to CodeClimate
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
